version: '{branch}-{build}'
build: off
configuration: Release
environment:
  matrix:
    - TOXENV: 'check'
      PYTHON_VERSION: '3.7'
      MINICONDA_HOME: 'C:\Miniconda'
      INSTALL_EXTRA_DEPS: 'pip install docutils check-manifest flake8 readme pygments sphinx_rtd_theme'
{% for env, config in tox_environments|dictsort %}{% if not config.cover %}
    - TOXENV: '{{ env }}-64'
      PYTHON_VERSION: '{{ config.python[-3:] }}'
      PYTHON_HOME: C:\{{ config.python.replace('.', '') }}-x64
      MINICONDA_HOME: C:\Miniconda-x64
    - TOXENV: '{{ env }}-32'
      PYTHON_VERSION: '{{ config.python[-3:] }}'
      PYTHON_HOME: C:\{{ config.python.replace('.', '') }}
      MINICONDA_HOME: C:\Miniconda
{% endif %}{% endfor %}

init:
  - ps: echo $env:TOXENV
install:
  # This quickly fails the job if there is another pipeline queued ahead of it
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
          https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
          Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
            throw "There are newer queued builds for this pull request, failing early." }
  - '%MINICONDA_HOME%\Scripts\conda config --set always_yes yes'
  - '%MINICONDA_HOME%\Scripts\conda update -q conda'
  - '%MINICONDA_HOME%\Scripts\conda create -q -p C:\pythontest python=%PYTHON_VERSION% pytest numpy libpython'
  # Remove file which conflicts with installation of package 'readme' on case-insensitive file systems
  - del C:\pythontest\Lib\site-packages\README
  - '%MINICONDA_HOME%\Scripts\activate C:\pythontest'
  - '%MINICONDA_HOME%\Scripts\conda install -q -c msys2 m2w64-toolchain'
  - python -m pip install --upgrade pip
  - pip install tox
  - python setup.py config_fc
  - python setup.py config --compiler=mingw32 --fcompiler=gfortran
  - python setup.py install

test_script:
  - python -m tox


### To enable remote debugging uncomment this:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

